const test=require('node:test');const assert=require('node:assert/strict');const S=require('../career-season.js');
const make=()=>S.migrate({used:true,team:'Test',coins:1000,round:1,rounds:4,table:Array.from({length:9},(_,i)=>({name:'Rival '+i,pace:1-i*.03,points:0}))});
function race(c,pos=1,flags={}){S.begin(c);S.advance(c);S.lap(c,120);S.advance(c);const rows=c.table.map(t=>({who:t.name,total:380}));rows.splice(pos-1,0,{who:'You',you:true,total:370,...flags});return rows;}
test('legacy migration preserves money, upgrades, points and championship progress',()=>{const c=S.migrate({coins:2350,power:3,aero:2,points:49,round:3,rounds:8});assert.equal(c.coins,2350);assert.equal(c.round,3);assert.equal(c.points,49);assert.equal(c.power,3);assert.equal(c.weekend.stage,'briefing');});
test('practice rewards only first valid lap and survives serialization',()=>{const c=make();S.begin(c);assert.equal(S.lap(c,-3),false);S.lap(c,140);assert.equal(c.coins,1250);const restored=S.migrate(JSON.parse(JSON.stringify(c)));S.lap(restored,135);assert.equal(restored.coins,1250);assert.equal(restored.weekend.practice.length,2);});
test('qualifying time determines grid; no time starts last',()=>{const c=make();S.begin(c);S.advance(c);S.advance(c);assert.equal(c.weekend.gridPosition,10);const d=make();race(d);assert.equal(d.weekend.gridPosition,1);assert.equal(new Set(d.weekend.grid.map(r=>r.ai)).size,10);});
test('championship scores once and round advances only after debrief',()=>{const c=make(),rows=race(c,2);assert.equal(S.score(c,rows),true);assert.equal(c.points,18);assert.equal(c.round,1);const funds=c.coins;assert.equal(S.score(c,rows),false);assert.equal(c.coins,funds);assert.equal(c.table[0].points,25);S.advance(c);assert.equal(c.round,2);assert.equal(c.weekend.stage,'briefing');});
test('disqualification and non-finish award no championship points',()=>{for(const flag of ['dsq','dnf']){const c=make();S.score(c,race(c,10,{[flag]:true}));assert.equal(c.points,0);assert.equal(c.last.objective,false);}});
test('full season, reload, archive and next contract retain upgrades',()=>{let c=make();c.power=3;for(let i=0;i<4;i++){S.score(c,race(c));S.advance(c);c=S.migrate(JSON.parse(JSON.stringify(c)));}assert.equal(c.round,5);assert.equal(c.points,100);assert.equal(c.history.length,4);assert.equal(S.nextSeason(c,{name:'Challenger',target:5,bonus:900},make().table),true);assert.equal(c.archive[0].rank,1);assert.equal(c.season,2);assert.equal(c.power,3);assert.equal(c.points,0);assert.equal(c.round,1);});
test('unfinished season cannot be reset by contract renewal',()=>{const c=make();assert.equal(S.nextSeason(c,{},[]),false);assert.equal(c.season,1);});
test('ties use countback of finishing positions',()=>{const c=make();S.score(c,race(c,1));c.table[0].points=25;assert.equal(S.standings(c)[0].you,true);});
